<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OU80H79" failures="2" tests="13" name="Test" time="0.512" errors="0" timestamp="2023-10-07T11:15:34 IST">
  <testcase classname="com.app.test.Fail_Test_Capture" name="test2" time="0.066"/>
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.061">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.016">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.011">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.008">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.007">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test3" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [Aite] but found [Aiite]">
      <![CDATA[java.lang.AssertionError: expected [Aite] but found [Aiite]
at com.app.test.Fail_Test_Capture.test3(Fail_Test_Capture.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.005">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.002">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.004">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.008">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.004">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.test.Fail_Test_Capture" name="test4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Aite] but found [Aiite]">
      <![CDATA[java.lang.AssertionError: expected [Aite] but found [Aiite]
at com.app.test.Fail_Test_Capture.test4(Fail_Test_Capture.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
